### ISSUE TITLE
F-Droid says Hashit is vulnerable

### ISSUE THREAD

**Issue by ghost** [ginkel/hashit#4]
Hi, when I try to install Hash it in F-Droid it says "known vulnerability".
They even moved it from F-droid Repository to Archived Repository.
What is the vulnerability ? can you please fix it ?

**Comment by ginkel** [comment]
Do you have any more details? This is the first time I ever hear about this...

**Comment by ghost** [comment]
I think its because SHA-1 is a broken algorithm.
Under "KnownVuln" stands "DisabledAlgorithm".

**Comment by ginkel** [comment]
You are referring to this Wiki page, right? https://f-droid.org/wiki/page/com.ginkel.hashit

The thing is, it's impossible to change this without breaking Password Hasher (Plus) compatibility (and an incompatible Android app isn't terribly useful).

I switched to Keepass2Android / KeeWeb to store my own passwords some time ago.

**Comment by ghost** [comment]
I was referring to this
![screenshot_2017-07-28-17-50-30](https://user-images.githubusercontent.com/22886346/28725398-95eaa812-73bd-11e7-8143-0ec57d04cca6.png)
Ok ich werd dann wohl auch zu keepass wechseln. Tschau :)

**Comment by ginkel** [comment]
Alles klar. Sorry, dass ich da keine bessere Lösung habe. :-/
